---
# Source: graphql/charts/graphql/templates/service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: graphql-service-account 
  namespace: ecommerce
---
# Source: graphql/charts/graphql/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: graphql-bff-service
  namespace: ecommerce
spec:
  selector:
    app: graphql-bff
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 3002
    targetPort: 3002
---
# Source: graphql/charts/graphql/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql-bff
  namespace: ecommerce
spec:
  replicas: 3
  selector:
    matchLabels:
      app: graphql-bff
      role: api
  template:
    metadata:
      labels:
        app: graphql-bff
        role: api
    spec:
      containers:
      - name: graphql-bff-container
        image: lukondefmwila/ecommerce-graphql:0.1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3002
