graphql:
  # Namespace object
  namespace: 
    enabled: true
    name: ecommerce
  # Service account
  serviceAccount: 
    enabled: true 
    name: graphql-service-account
    namespace: ecommerce
  # Deployment object
  deployment:
    enabled: true
    name: graphql-bff
    namespace: ecommerce
    replicas: 3
    appName: graphql-bff
    role: api
    containerName: graphql-bff-container
    image: lukondefmwila/ecommerce-graphql:0.1.0
    port: 3002
  # Service object
  service:
    enabled: true
    name: graphql-bff-service
    namespace: ecommerce
    appName: graphql-bff
    type: LoadBalancer # ClusterIP
    servicePort: 3002
    targetPort: 3002