products:
  # Namespace object
  namespace: 
    enabled: false
  # Service Account object
  serviceAccount: 
    enabled: true
    name: products-service-account
    namespace: ecommerce
  # Deployment object
  deployment:
    enabled: true
    name: products
    namespace: ecommerce
    replicas: 3
    appName: products
    role: api
    containerName: products-container
    image: lukondefmwila/ecommerce-products:0.1.0
    port: 3004
  # Service object
  service:
    enabled: true
    name: products-service
    namespace: ecommerce
    appName: products
    type: ClusterIP
    servicePort: 3004
    targetPort: 3004
  
  